Repository VM-Chinese-translate-group/Cottage-Witch, pull requests merged in 2024-02, with the labels that each got.

#9 图片汉化
  zh-CN/kubejs/assets/cottagewitch/textures/depositextract.png
Labels: approve, ready to merge, resource

#7 tips
  zh-CN/kubejs/assets/cottagewitch/tips/achievements.json
  zh-CN/kubejs/assets/cottagewitch/tips/akashic.json
  zh-CN/kubejs/assets/cottagewitch/tips/amethyst.json
  zh-CN/kubejs/assets/cottagewitch/tips/anvil.json
  zh-CN/kubejs/assets/cottagewitch/tips/blaze.json
  zh-CN/kubejs/assets/cottagewitch/tips/campfirelytra.json
  zh-CN/kubejs/assets/cottagewitch/tips/carts.json
  zh-CN/kubejs/assets/cottagewitch/tips/chatitems.json
  zh-CN/kubejs/assets/cottagewitch/tips/composter.json
  zh-CN/kubejs/assets/cottagewitch/tips/curios.json
  zh-CN/kubejs/assets/cottagewitch/tips/dispensers.json
  zh-CN/kubejs/assets/cottagewitch/tips/emotes.json
  zh-CN/kubejs/assets/cottagewitch/tips/enchanting.json
  zh-CN/kubejs/assets/cottagewitch/tips/fairyrings.json
  zh-CN/kubejs/assets/cottagewitch/tips/frames.json
  zh-CN/kubejs/assets/cottagewitch/tips/ghasts.json
  zh-CN/kubejs/assets/cottagewitch/tips/gravel.json
  zh-CN/kubejs/assets/cottagewitch/tips/hoeharvest.json
  zh-CN/kubejs/assets/cottagewitch/tips/infinity.json
  zh-CN/kubejs/assets/cottagewitch/tips/inventorymove.json
  zh-CN/kubejs/assets/cottagewitch/tips/inventorysort.json
  zh-CN/kubejs/assets/cottagewitch/tips/lilypads.json
  zh-CN/kubejs/assets/cottagewitch/tips/lootbeams.json
  zh-CN/kubejs/assets/cottagewitch/tips/lootr.json
  zh-CN/kubejs/assets/cottagewitch/tips/modconfig.json
  zh-CN/kubejs/assets/cottagewitch/tips/notes.json
  zh-CN/kubejs/assets/cottagewitch/tips/obsidianboat.json
  zh-CN/kubejs/assets/cottagewitch/tips/oculus.json
  zh-CN/kubejs/assets/cottagewitch/tips/paintings.json
  zh-CN/kubejs/assets/cottagewitch/tips/pistons.json
  zh-CN/kubejs/assets/cottagewitch/tips/poisonbaby.json
  zh-CN/kubejs/assets/cottagewitch/tips/preventspawn.json
  zh-CN/kubejs/assets/cottagewitch/tips/quests.json
  zh-CN/kubejs/assets/cottagewitch/tips/reaping.json
  zh-CN/kubejs/assets/cottagewitch/tips/shulkers.json
  zh-CN/kubejs/assets/cottagewitch/tips/shulkies.json
  zh-CN/kubejs/assets/cottagewitch/tips/signediting.json
  zh-CN/kubejs/assets/cottagewitch/tips/skulls.json
  zh-CN/kubejs/assets/cottagewitch/tips/snad.json
  zh-CN/kubejs/assets/cottagewitch/tips/soundmuffler.json
  zh-CN/kubejs/assets/cottagewitch/tips/thatch.json
  zh-CN/kubejs/assets/cottagewitch/tips/tiab.json
  zh-CN/kubejs/assets/cottagewitch/tips/veinminer.json
  zh-CN/kubejs/assets/cottagewitch/tips/villagers.json
  zh-CN/kubejs/assets/cottagewitch/tips/voicechat.json
  zh-CN/kubejs/assets/cottagewitch/tips/void.json
  zh-CN/kubejs/assets/cottagewitch/tips/watercreatures.json
Labels: approve, ready to merge

#5 New Crowdin updates
  zh-CN/kubejs/assets/ars_nouveau/lang/zh_cn.json
  zh-CN/kubejs/assets/better_fishing_rods/lang/zh_cn.json
  zh-CN/kubejs/assets/betteramethyst/lang/zh_cn.json
  zh-CN/kubejs/assets/bettertags/lang/zh_cn.json
  zh-CN/kubejs/assets/block_variants/lang/zh_cn.json
  zh-CN/kubejs/assets/colorfulazaleas/lang/zh_cn.json
  zh-CN/kubejs/assets/convenientcurioscontainer/lang/zh_cn.json
  zh-CN/kubejs/assets/domesticationinnovation/lang/zh_cn.json
  zh-CN/kubejs/assets/experienceobelisk/lang/zh_cn.json
  zh-CN/kubejs/assets/gildednetherite/lang/zh_cn.json
  zh-CN/kubejs/assets/luphieclutteredmod/lang/zh_cn.json
  zh-CN/kubejs/assets/mermod/lang/zh_cn.json
  zh-CN/kubejs/assets/mythicmounts/lang/zh_cn.json
  zh-CN/kubejs/assets/portablejukebox/lang/zh_cn.json
  zh-CN/kubejs/assets/quests/lang/zh_cn.json
  zh-CN/kubejs/assets/reaping/lang/zh_cn.json
  zh-CN/kubejs/assets/ring_of_enderchest/lang/zh_cn.json
  zh-CN/kubejs/assets/sculktransporting/lang/zh_cn.json
  zh-CN/kubejs/assets/seedpouch/lang/zh_cn.json
  zh-CN/kubejs/assets/shorkmod/lang/zh_cn.json
  zh-CN/kubejs/assets/snailmail/lang/zh_cn.json
  zh-CN/kubejs/assets/sprout/lang/zh_cn.json
Labels: Crowdin, in progress
